{% set name = "buildbot-grid-view" %}
{% set version = "2.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: d0ee62554c4e3068e9f6e8f4eee828b998051191f2e7d5c5a15a1e2c995f13d5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - pip
    - python >3.5
    - buildbot-pkg
  run:
    - python >3.5
    - buildbot-pkg
    - buildbot-www

test:
  imports:
    - buildbot_grid_view

about:
  home: "https://buildbot.net/"
  license: "GNU General Public (GPL)"
  license_family: "LGPL"
  license_file: "LICENSE"
  summary: "Buildbot Grid View plugin"
  doc_url: "https://docs.buildbot.net"

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
